name: build script for quiz.c		

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4	

      - name: create bin folder
        run: mkdir bin	

      - name: build quiz			
        run: make bin/quiz		

      - name: upload binary			
        uses: actions/upload-artifact@v4	
        with:
          name: Quiz			
          path: ./bin				

  test:
    runs-on: ubuntu-latest
    steps:
      - name: run quiz command
        run: quiz

