name: build script for quiz.c		

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4	

      - name: Build quiz			
        run: gcc -o quiz quiz.c		

      - name: Upload binary			
        uses: actions/upload-artifact@v4	
        with:
          name: quiz			
          path: ./quiz			

      - name: Test --help flag
        run: ./quiz --help

      - name: Test -1 flag
        run: ./quiz -1

      - name: Test answering question 1 correctly
        run: ./quiz -1 "No"

      - name: Test answering question 1 incorrectly
        run: ./quiz -1 "Yes"

      - name: Test -2 flag
        run: ./quiz -2

      - name: Test answering question 2 correctly
        run: ./quiz -2 "Yes"

      - name: Test answering question 2 incorrectly
        run: ./quiz -2 "What sky?"

      - name: Test -3 flag
        run: ./quiz -3

      - name: Test answering question 3 correctly
        run: ./quiz -3 "3"

      - name: Test answering question 3 incorrectly
        run: ./quiz -3 "2"